### PR TITLE
Merge upstream JohnPapa guide

### PR DESCRIPTION
**Pull request by alexlrobertson**

### CODE REVIEW

**Comment by JackMorrissey** [comment]
:cake: Fine by me. Gonna have to reread to make sure nothing actually changed that we're doing 
@michaelanthonymain You're the keeper of this. Thoughts?

**Comment by tykowale** [comment]
:cake:

**Comment by alexlrobertson** [comment]
Any update? Should I merge?

**Comment by alexlrobertson** [comment]
Any update here?

**Comment by tykowale** [comment]
I say go for it!

**Comment by JackMorrissey** [comment]
Lets do it.

**Pull request merged**
